Run meson compile -C build -j$(nproc)
  
ninja: Entering directory `/home/runner/work/4jcraft/4jcraft/build'
[1/185] Generating subprojects/shiggy/unpack-archive with a custom command
[2/185] Generating Minecraft.Assets/Minecraft.Assets_Localisation with a custom command
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/ja-JP/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/pt-BR/strings.lang
Processed 2268 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/en-EN/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/zh-CHT/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/es-ES/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/fr-FR/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/ko-KR/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/de-DE/strings.lang
Processed 1885 strings from /home/runner/work/4jcraft/4jcraft/Minecraft.Assets/Windows64Media/loc/it-IT/strings.lang
Processed 9 languages
Wrote 1325173 bytes to Minecraft.Assets/languages.loc
Generated Minecraft.Assets/strings.h with 2268 defines
[3/185] Generating subprojects/simdutf/amalgamate with a custom command
SCRIPTPATH=/home/runner/work/4jcraft/4jcraft/subprojects/simdutf/singleheader PROJECTPATH=/home/runner/work/4jcraft/4jcraft/subprojects/simdutf
We are about to amalgamate all simdutf files into one source file.
See https://www.sqlite.org/amalgamation.html and https://en.wikipedia.org/wiki/Single_Compilation_Unit for rationale.
timestamp is 2026-03-12 20:46:37 -0400
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/simdutf.h
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/simdutf.cpp
Copying additional files to /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/simdutf_c.h
Processing amalgamation_demo.cpp
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/amalgamation_demo.cpp
Processing README.md
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/README.md
Processing amalgamation_demo.c
Creating /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf/amalgamation_demo.c
Done with all files generation.
Files have been written to directory: /home/runner/work/4jcraft/4jcraft/build/subprojects/simdutf
[4/185] Compiling C++ object subprojects/4jlibs/builddef/lib4J_Profile.a.p/meson-generated_4J_Profile-unity0.cpp.o
[5/185] Compiling C++ object subprojects/4jlibs/builddef/lib4J_Input.a.p/meson-generated_4J_Input-unity0.cpp.o
[6/185] Compiling C++ object subprojects/4jlibs/builddef/lib4J_Render.a.p/meson-generated_4J_Render-unity0.cpp.o
FAILED: [code=1] subprojects/4jlibs/builddef/lib4J_Render.a.p/meson-generated_4J_Render-unity0.cpp.o 
em++ -Isubprojects/4jlibs/builddef/lib4J_Render.a.p -Isubprojects/4jlibs/builddef -I../subprojects/4jlibs/builddef -I../subprojects/4jlibs/4J.Render -I../subprojects/4jlibs/4J.Common -fdiagnostics-color=always -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -D_FILE_OFFSET_BITS=64 -std=c++23 -O3 -O2 -std=c++17 -fPIC -pthread -fpermissive -Wshift-count-overflow -pipe -DSPLIT_SAVES -D_LARGE_WORLDS -D_EXTENDED_ACHIEVEMENTS -D_DEBUG_MENUS_ENABLED -D_DEBUG -DDEBUG -include /home/runner/work/4jcraft/4jcraft/subprojects/4jlibs/builddef/../4J.Render/stdafx.h -MD -MQ subprojects/4jlibs/builddef/lib4J_Render.a.p/meson-generated_4J_Render-unity0.cpp.o -MF subprojects/4jlibs/builddef/lib4J_Render.a.p/meson-generated_4J_Render-unity0.cpp.o.d -o subprojects/4jlibs/builddef/lib4J_Render.a.p/meson-generated_4J_Render-unity0.cpp.o -c subprojects/4jlibs/builddef/lib4J_Render.a.p/4J_Render-unity0.cpp
In file included from subprojects/4jlibs/builddef/lib4J_Render.a.p/4J_Render-unity0.cpp:1:
/home/runner/work/4jcraft/4jcraft/build/../subprojects/4jlibs/builddef/../4J.Render/4J_Render.cpp:24:10: fatal error: 'glm/glm.hpp' file not found
   24 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
1 error generated.
[7/185] Compiling C++ object subprojects/4jlibs/builddef/lib4J_Storage.a.p/meson-generated_4J_Storage-unity0.cpp.o
[8/185] Compiling C++ object subprojects/simdutf/libsimdutf.a.p/meson-generated_simdutf-unity0.cpp.o
[9/185] Compiling C++ object Minecraft.World/libMinecraft.World.a.p/meson-generated_Minecraft.World-unity0.cpp.o
ports:INFO: retrieving port: zlib from https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz
ports:INFO: unpacking port: zlib
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libz.a... (this will be cached in "/home/runner/work/_temp/5e162e1d-ccb3-4e5c-a359-0102eaba9c83/emsdk-main/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a" for subsequent builds)
system_libs:INFO: compiled 15 inputs in 1.62s
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2-mt.a... (this will be cached in "/home/runner/work/_temp/5e162e1d-ccb3-4e5c-a359-0102eaba9c83/emsdk-main/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2-mt.a" for subsequent builds)
system_libs:INFO: compiled 119 inputs in 11.55s
cache:INFO:  - ok
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /opt/hostedtoolcache/Python/3.12.13/x64/bin/ninja -C /home/runner/work/4jcraft/4jcraft/build -j 4
Error: Process completed with exit code 1.
